### ISSUE TITLE
Add liquidity to empty pool prompt wrong exchange rate

### ISSUE THREAD

**Issue by bota87** [Uniswap/uniswap-interface#1102] opened 2020-09-13 16:36 UTC
I'm trying to add liquidity to DAI-STORJ Pair.
For 10 DAI it ask 2236 STORJ (0.0045 DAI per STORJ) but the actual price is more than 100x higher (0.50$)

This is a pool with only 2 transactions, add 10 DAI / 50 STORJ and remove the same amount after 3 days

[Here](https://uniswap.info/pair/0x136ebe33c2f3992ce2ca9bf66349264be2c63240) the uniswap.info pair page

I think in this case the liquidity provider should be able to choose the "initial" price like when a new pair is created

**Comment by moodysalem** [comment] 2021-01-30 01:46
Duplicate of https://github.com/Uniswap/uniswap-interface/issues/1079

**Closed by moodysalem** 2021-01-30 01:46 UTC
Labels: bug
