### ISSUE TITLE
Crash report: `TypeError: t.replaceAll is not a function`

### ISSUE THREAD

**Issue by goopong** [Uniswap/uniswap-interface#2354] opened 2021-09-15 15:37 UTC
## URL
  
https://app.uniswap.org/#/vote

## Error

```
TypeError: t.replaceAll is not a function
```

## Stacktrace

```
TypeError: t.replaceAll is not a function
    at https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:488937
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:488422
    at Object.To [as useMemo] (https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1661571)
    at https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1581043
    at Vw (https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:488145)
    at Kw (https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:489901)
    at NA (https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:684668)
    at no (https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1656838)
    at zo (https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1666405)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 11; V2038) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "83.0.4103.106",
    "major": "83"
  },
  "engine": {
    "name": "Blink",
    "version": "83.0.4103.106"
  },
  "os": {
    "name": "Android",
    "version": "11"
  },
  "device": {
    "model": "V2038",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by zzmp** [comment] 2021-09-15 17:44
Duplicate of #2308

**Closed by zzmp** 2021-09-15 17:44 UTC
