### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by IMPULS77** [Uniswap/uniswap-interface#1654] opened 2021-05-19 20:50 UTC
## URL
  
https://app.uniswap.org/#/swap?exactField=output&exactAmount=3000&outputCurrency=0xada86b1b313d1d5267e3fc0bb303f0a2b66d0ea7&use=V2

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": ""
  },
  "OUTPUT": {
    "currencyId": "0xADA86b1b313D1D5267E3FC0bB303f0A2b66D0Ea7"
  },
  "independentField": "OUTPUT",
  "typedValue": "3000",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Os (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1512461)
    at Cu (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1524273)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1544890)
    at Hi (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1467248)
    at Pu (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1522231)
    at bu (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1518317)
    at https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1467471
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1544890)
    at Hi (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1467248)
    at Xi (https://app.uniswap.org/static/js/4.1d476024.chunk.js:2:1467416)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.212",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.212"
  },
  "os": {
    "name": "Windows",
    "version": "7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by moodysalem** [comment] 2021-05-19 22:34
dupe of https://github.com/Uniswap/uniswap-interface/issues/1576

**Closed by moodysalem** 2021-05-19 22:34 UTC
