### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`

### ISSUE THREAD

**Issue by hoylairen** [Uniswap/uniswap-interface#1707] opened 2021-05-26 00:47 UTC
## URL
  
https://app.uniswap.org/#/pool

## Error

```
NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at ks (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1509104)
    at gs (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1508602)
    at ju (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1521383)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1542203)
    at Hi (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1464561)
    at Pu (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1519544)
    at mu (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1515630)
    at https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1464784
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1542203)
    at Hi (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1464561)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.93",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.93"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by moodysalem** [comment] 2021-05-26 17:37
Can you reproduce?

**Comment by moodysalem** [comment] 2021-05-27 16:18
Duplicate of https://github.com/Uniswap/uniswap-interface/issues/1576

**Closed by moodysalem** 2021-05-27 16:18 UTC
