### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by Thendog26** [Uniswap/uniswap-interface#2194] opened 2021-08-11 07:10 UTC
Produced the following issue by selecting ETH to INCH and spam typing into the input box by accident. :)

## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0x111111111117dC0aa78b770fA6A738034120C302"
  },
  "independentField": "INPUT",
  "typedValue": "484290384029734927409202972097029374202974209702740922094",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
t.default@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:95424
t@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:78756
ne</t.fromFractionalAmount@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:78949
ue</r.quote@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:82002
me@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:84469
e@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:273320
me</e.bestTradeExactIn@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:274718
Pd/E</<@https://app.uniswap.org/static/js/main.e432ba44.chunk.js:1:167864
To@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1665632
t.useMemo@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1585104
Pd/E<@https://app.uniswap.org/static/js/main.e432ba44.chunk.js:1:167666
Pd@https://app.uniswap.org/static/js/main.e432ba44.chunk.js:1:167991
$T@https://app.uniswap.org/static/js/main.e432ba44.chunk.js:1:649610
no@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1660899
zo@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1670466
Vu@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1714348
Ss@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1700533
As@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1700461
_s@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1700322
bs@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1697288
Xi/<@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1646667
t.unstable_runWithPriority@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1724086
qi@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1646444
Xi@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1646614
Vi@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1646547
Ne/<@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1718045
Ne@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1718050
Be@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1616903
Mn/<@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1638076
Mn@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1638082
Yt@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1626155
$t@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1625381
t.unstable_runWithPriority@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1724086
qi@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1646444
Ie@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1717842
Zt@https://app.uniswap.org/static/js/4.d35f88da.chunk.js:2:1625173

```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0",
  "browser": {
    "name": "Firefox",
    "version": "90.0",
    "major": "90"
  },
  "engine": {
    "name": "Gecko",
    "version": "90.0"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by Thendog26** [comment] 2021-08-11 12:43
Seems to crash when I type more than 56 characters in.

**Comment by zzmp** [comment] 2021-08-12 02:09
Duplicate of #2103

**Closed by zzmp** 2021-08-12 02:09 UTC
