### ISSUE TITLE
RBF transactions are never cleared from the pending transaction queue.

### ISSUE THREAD

**Issue by JFrankfurt** [Uniswap/uniswap-interface#1141] opened 2020-10-01 05:23 UTC
**Bug Description**
If a user replaces a transaction with a higher fee, the queue of transactions that the UI keeps will not update when the tx nonce is completed by another transaction.

**Steps to Reproduce**
1. broadcast a transaction and don't mine it
2. broadcast a second transaction with the same nonce and mine it
3. observe continually pending tx

**Expected Behavior**
I would expect the UI to realize the user had RBF'd and show the transaction as complete.

**Comment by heyJonBray** [comment] 2020-10-01 14:36
Looks like the UI should check the transaction with etherscan.io at certain intervals and adjust accordingly.

**Comment by moodysalem** [comment] 2020-10-01 15:53
Duplicate of https://github.com/Uniswap/uniswap-interface/issues/1016

**Closed by moodysalem** 2020-10-01 15:53 UTC
Labels: bug

**Comment by CivelXu** [comment] 2021-03-19 12:08
I have same issue， How to solve it ?

**Comment by moodysalem** [comment] 2021-03-19 17:11
> I have same issue， How to solve it ?

Hit `(clear)` in the recent transactions dialog
