### ISSUE TITLE
Show pool size on add add/join pool page

### ISSUE THREAD

**Issue by callil** [Uniswap/uniswap-interface#796] opened 2020-05-19 01:08 UTC
Add this info in addition to current rates.

**Comment by NoahZinsmeister** [comment] 2020-05-20 16:21
can we close this in favor of #813?

**Comment by moodysalem** [comment] 2021-01-30 02:02
duplicate of https://github.com/Uniswap/uniswap-interface/issues/959

**Closed by moodysalem** 2021-01-30 02:02 UTC
Labels: improvement
