### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by pongit** [Uniswap/uniswap-interface#1946] opened 2021-07-01 20:20 UTC
## URL
  
https://app.uniswap.org/#/add/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2/ETH

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:89845)
    at t.r.sortsBefore (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:78461)
    at https://app.uniswap.org/static/js/main.3a7392b6.chunk.js:1:330267
    at Object.xo [as useMemo] (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1596760)
    at t.useMemo (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1516232)
    at kv (https://app.uniswap.org/static/js/main.3a7392b6.chunk.js:1:330240)
    at zg (https://app.uniswap.org/static/js/main.3a7392b6.chunk.js:1:358374)
    at no (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1592027)
    at zo (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1601594)
    at Vu (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1645476)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "91.0.4472.114",
    "major": "91"
  },
  "engine": {
    "name": "Blink",
    "version": "91.0.4472.114"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment] 2021-07-06 16:47
thanks for reporting! dupe of #1763

**Closed by willhennessy** 2021-07-06 16:47 UTC
