### ISSUE TITLE
Unable to remove liquidity from token/token pair (one is deflationary)

### ISSUE THREAD

**Issue by timbilt** [Uniswap/uniswap-interface#1212] opened 2020-11-15 16:18 UTC
**Bug Description**
I bought two tokens, YFFS and FECORE on uniswap. They are both from the same project and they created a YFFS/FECORE pair. I added liquidity to that pair here: https://app.uniswap.org/#/add/0x704b5267FAE30C40Fd0A4b14D83E414B4A920afA/0x90D702f071d2af33032943137AD0aB4280705817

When I go to manage the pool now, after approving the transaction, clicking on Confirm does nothing.

**Steps to Reproduce**
1. Go to https://app.uniswap.org/#/add/0x704b5267FAE30C40Fd0A4b14D83E414B4A920afA/0x90D702f071d2af33032943137AD0aB4280705817
2. Add liquidity with equal value of YFFS and FECORE.
3. Try to remove the liquidity by managing the pool.
4. After approving, click Confirm.
5. Now nothing happens and your transaction is not executed, and the following messages appear in the browser console:
> **MetaMask - RPC Error: execution reverted: UniswapV2: TRANSFER_FAILED** 
> **estimateGas failed removeLiquidityWithPermit** 
> **This transaction would fail. Please contact support.**

**Expected Behavior**
I expected the transaction to be executed after clicking Confirm and for me to receive my YFFS and FECORE in my metamask wallet.

**Additional Info**
I followed the steps outlined in [Issue 835](https://github.com/Uniswap/uniswap-interface/issues/835). When removing liquidity, Metamask asks to confirm. Above the Confirm button is an alert stating:
> **ALERT: Transaction Error. Exception thrown in contract code.**

I don't want to click confirm because the gas fee is pretty high (approx. $150), and I don't want to risk losing that money if it's gonna fail.

**Comment by pkmelee337** [comment] 2020-11-18 10:25
Just encountered the same problem. This has nothing to do with uniswap, but this is because the YFFS/FECORE pair is locked. You are able to stake them on https://fecore.finance/ and from what I've heard they might be creating a balancer pool or something to sell the locked LP. You can find more information on the YFFS telegram if you like.

**Comment by moodysalem** [comment] 2021-01-30 01:48
Duplicate of https://github.com/Uniswap/uniswap-interface/issues/1257
Related to https://github.com/Uniswap/uniswap-interface/issues/1291

**Closed by moodysalem** 2021-01-30 01:48 UTC
Labels: bug
