### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by vagabond0303** [Uniswap/uniswap-interface#1942] opened 2021-07-01 12:04 UTC
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0xbF7A7169562078c96f0eC1A8aFD6aE50f12e5A99"
  },
  "OUTPUT": {
    "currencyId": "0x5592EC0cfb4dbc12D3aB100b257153436a1f0FEa"
  },
  "independentField": "INPUT",
  "typedValue": "22486.800653776865153774",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:89845)
    at new t (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:74081)
    at Function.t.fromFractionalAmount (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:74274)
    at t.r.quote (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:77309)
    at B (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:79405)
    at e.get (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:165694)
    at https://app.uniswap.org/static/js/main.3a7392b6.chunk.js:1:523612
    at Object.xo [as useMemo] (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1596760)
    at t.useMemo (https://app.uniswap.org/static/js/4.72d773b4.chunk.js:2:1516232)
    at rI (https://app.uniswap.org/static/js/main.3a7392b6.chunk.js:1:523563)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "91.0.4472.124",
    "major": "91"
  },
  "engine": {
    "name": "Blink",
    "version": "91.0.4472.124"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment] 2021-07-06 16:51
thank you! dupe of #1843

**Closed by willhennessy** 2021-07-06 16:51 UTC
