### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by Tuananh11021986** [Uniswap/uniswap-interface#2025] opened 2021-07-12 22:10 UTC
## URL
  
https://app.uniswap.org/#/add/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2/ETH

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.499580c4.chunk.js:2:86932)
    at t.r.sortsBefore (https://app.uniswap.org/static/js/4.499580c4.chunk.js:2:75669)
    at https://app.uniswap.org/static/js/main.f50c9663.chunk.js:1:318743
    at Object._o [as useMemo] (https://app.uniswap.org/static/js/4.499580c4.chunk.js:2:1477438)
    at t.useMemo (https://app.uniswap.org/static/js/4.499580c4.chunk.js:2:1396910)
    at _O (https://app.uniswap.org/static/js/main.f50c9663.chunk.js:1:318716)
    at Xv (https://app.uniswap.org/static/js/main.f50c9663.chunk.js:1:360062)
    at no (https://app.uniswap.org/static/js/4.499580c4.chunk.js:2:1472705)
    at zo (https://app.uniswap.org/static/js/4.499580c4.chunk.js:2:1482272)
    at Vu (https://app.uniswap.org/static/js/4.499580c4.chunk.js:2:1526154)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 9; SM-G955U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.120 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "91.0.4472.120",
    "major": "91"
  },
  "engine": {
    "name": "Blink",
    "version": "91.0.4472.120"
  },
  "os": {
    "name": "Android",
    "version": "9"
  },
  "device": {
    "vendor": "Samsung",
    "model": "SM-G955U",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by moodysalem** [comment] 2021-07-26 12:35
Duplicate of https://github.com/Uniswap/uniswap-interface/issues/1763

**Closed by moodysalem** 2021-07-26 12:35 UTC
