### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by safissefa** [Uniswap/uniswap-interface#1708] opened 2021-05-26 02:02 UTC
#1707  URL
  
https://app.uniswap.org/#/find?origin=/migrate/v2

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at HTMLDivElement.removeChild (<anonymous>)
    at Os (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1509774)
    at ju (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1521586)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1542203)
    at Hi (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1464561)
    at Pu (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1519544)
    at mu (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1515630)
    at https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1464784
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1542203)
    at Hi (https://app.uniswap.org/static/js/4.da09fbf7.chunk.js:2:1464561)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 8.1.0; CPH1909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.210",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.210"
  },
  "os": {
    "name": "Android",
    "version": "8.1.0"
  },
  "device": {
    "vendor": "OPPO",
    "model": "CPH1909",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by moodysalem** [comment] 2021-05-26 17:37
Can you reproduce?

**Comment by moodysalem** [comment] 2021-05-27 16:17
Duplicate of https://github.com/Uniswap/uniswap-interface/issues/1576

**Closed by moodysalem** 2021-05-27 16:17 UTC
