### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by richard-thai** [Uniswap/uniswap-interface#1550] opened 2021-05-12 21:21 UTC
**Bug Description**
  
App crashed

**Steps to Reproduce**

1. Go to ...
2. Click on ...
   ...
   
**Error**

```
Error: Invariant failed
```

**Stacktrace**

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.d6a485e3.chunk.js:2:84980)
    at Function.t.swapCallParameters (https://app.uniswap.org/static/js/4.d6a485e3.chunk.js:2:161271)
    at https://app.uniswap.org/static/js/main.75c59955.chunk.js:1:480880
    at Object.Eo [as useMemo] (https://app.uniswap.org/static/js/4.d6a485e3.chunk.js:2:1485841)
    at t.useMemo (https://app.uniswap.org/static/js/4.d6a485e3.chunk.js:2:1405295)
    at https://app.uniswap.org/static/js/main.75c59955.chunk.js:1:480351
    at CA (https://app.uniswap.org/static/js/main.75c59955.chunk.js:1:481198)
    at SA (https://app.uniswap.org/static/js/main.75c59955.chunk.js:1:490913)
    at no (https://app.uniswap.org/static/js/4.d6a485e3.chunk.js:2:1481108)
    at zo (https://app.uniswap.org/static/js/4.d6a485e3.chunk.js:2:1490675)
```

**Device data**

```json5
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.93",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.93"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by moodysalem** [comment] 2021-05-12 21:29
Dupe of https://github.com/Uniswap/uniswap-interface/issues/1548

**Closed by moodysalem** 2021-05-12 21:29 UTC
