### ISSUE TITLE
Crash report: `RangeError: Division by zero`

### ISSUE THREAD

**Issue by makerzy** [Uniswap/uniswap-interface#1532] opened 2021-05-12 16:01 UTC
**Bug Description**
  
App crashed

**Steps to Reproduce**

1. Go to ...
2. Click on ...
   ...
   
**Error**

```
RangeError: Division by zero
```

**Stacktrace**

```
RangeError: Division by zero
    at Function.value (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:45358)
    at e.get (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:5681)
    at t.r.quote (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:8348)
    at https://app.uniswap.org/static/js/main.df292876.chunk.js:1:522472
    at Object.Eo [as useMemo] (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1477347)
    at t.useMemo (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1396801)
    at https://app.uniswap.org/static/js/main.df292876.chunk.js:1:522269
    at oS (https://app.uniswap.org/static/js/main.df292876.chunk.js:1:523933)
    at no (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1472614)
    at zo (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1482181)
```

**Comment by moodysalem** [comment] 2021-05-13 22:55
duplicate of https://github.com/Uniswap/uniswap-interface/issues/1566

**Closed by moodysalem** 2021-05-13 22:55 UTC
Labels: bug
