### ISSUE TITLE
UI chrome problem

### ISSUE THREAD

**Issue by thebunga** [Uniswap/uniswap-interface#1286] opened 2021-01-26 07:19 UTC
![image](https://user-images.githubusercontent.com/69405215/105812748-94560b00-5f63-11eb-8320-c13b8b0027a6.png)

When trying to upload new coin address, this screen appears but DOES NOT allow me to scroll down to accept and proceed.  Is there a bug?  How to remedy?  Thanks.

**Comment by moodysalem** [comment] 2021-01-29 21:22
Duplicate of https://github.com/Uniswap/uniswap-interface/issues/1272

**Closed by moodysalem** 2021-01-29 21:22 UTC
Labels: bug, p0
