### ISSUE TITLE
Crash report: `Invariant failed`

### ISSUE THREAD

**Issue by mime29** [Uniswap/uniswap-interface#1523] opened 2021-05-12 06:48 UTC
**Bug Description**
  
App crashed

**Steps to Reproduce**

1. Go to ...
2. Click on ...
   ...
   
**Error**

```
Error: Invariant failed
```

**Stacktrace**

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:98269)
    at Function.e.getTickAtSqrtRatio (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1875081)
    at t.priceToClosestTick (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1904372)
    at Zg (https://app.uniswap.org/static/js/main.1cc75114.chunk.js:1:309066)
    at https://app.uniswap.org/static/js/main.1cc75114.chunk.js:1:311483
    at Object.Eo [as useMemo] (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1477347)
    at t.useMemo (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1396801)
    at ny (https://app.uniswap.org/static/js/main.1cc75114.chunk.js:1:311356)
    at Tw (https://app.uniswap.org/static/js/main.1cc75114.chunk.js:1:337731)
    at no (https://app.uniswap.org/static/js/4.7be9d8b6.chunk.js:2:1472614)
```

**Device data**

```json5
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.93",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.93"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by tannerevans** [comment] 2021-05-12 22:26
May be related to the issue in #1504

**Comment by moodysalem** [comment] 2021-05-14 15:31
duplicate of https://github.com/Uniswap/uniswap-interface/issues/1523

**Comment by moodysalem** [comment] 2021-05-19 22:29
Not sure what this is anymore or if it's fixed, closing unless someone can repro

**Closed by moodysalem** 2021-05-19 22:29 UTC
Labels: bug
