### ISSUE TITLE
Add share UI/UX 

### ISSUE THREAD

**Issue by callil** [Uniswap/uniswap-interface#787] opened 2020-05-18 19:30 UTC
For any selected state in the UI. Create a UI affordance to share it via url or other means. 

Primarily for swap, but should appear for all other sections of the site and provide a modal to review the link and what you're sharing.

**Comment by moodysalem** [comment] 2021-01-30 03:34
imo duplicate of https://github.com/Uniswap/uniswap-interface/issues/972

**Closed by moodysalem** 2021-01-30 03:34 UTC
Labels: improvement
