### ISSUE TITLE
How do we solve the discoverability problem of new tokens?

### ISSUE THREAD

**Issue by gonchs** [Uniswap/uniswap-interface#162] opened 2018-12-09 19:55 UTC
How do we solve the discoverability problem of new tokens?

The ideal scenario would be to show a list of all compatible Uniswap contracts (tokens) sorted by the available liquidity without the need to [hardcode them into the frontend code](https://github.com/Uniswap/uniswap-frontend/blob/7b8252f9caaf0852e99ae3de01328f1ee32ffb36/src/ducks/addresses.js). The frontend code should discover them in its own in some way. This would also help prevent centralization and avoid censorship - no reasonable exchange operator would ever list a clear security token due to the recent SEC events with EtherDelta. If the frontend was able to discover new tokens automatically, anyone could just do a git clone, run it locally and trade whatever they want, without censorship.

For example, if I deploy a new contract to trade token XYZ and fund it with the liquidity of $100k, Uniswap interface should pick this up automatically, without any frontend code changes and show it.

Currently, I have two ideas. Both may have flaws or not be possible due to various reasons. Perhaps someone smarter than me could expand on them?

1) Create a permissionless token registry contract to which **anyone** can add a new token contract address. Added addresses may never be removed to prevent censorship. Frontend would query this contract and only show tokens which meet some threshold - for example, they have enough liquidity or trading volume in them.

2) No idea if this is possible or not. Could the interface somehow try to scan the blockchain for the contracts which look like Uniswap? Maybe scan the N number of last blocks (not sure how long it would take) for the events emitted by Uniswap contracts (TokenPurchase, EthPurchase, etc)? The downside with this approach, if even possible, would be that it would only show the contracts which recently had any activity.

3) Any better idea?

**Comment by gonchs** [comment] 2018-12-09 22:11
Good point. But does it even have a solution? What differentiates the "real" token from the "fake" one?

- If we fetch a [list of tokens from etherscan](https://etherscan.io/tokens?sort=24h_volume_usd&order=desc) to verify them, it will prevent the listing of completely new tokens.
- If we cross-check the tokens with other known exchanges, it will again prevent the listing of new tokens.
- If we check the number of holders or transfers of a contract, all of them could be fake.

**Comment by osyed** [comment] 2018-12-13 21:38
I would suggest using a backend service which provides the list of tokens to the frontend. The backend should scan the Token summary fields for all tokens in the list from etherscan.io and return these to the frontend. These fields include things like Reputation and links to official Website, Twitter, Reddit, etc. If this kind of information is presented to the user, it would be up to the user to determine if this is the token they were looking for. Also a checkmark can be provided with tokens based on the Reputation from etherscan.io. The real DAI would have earned a checkmark and a duplicate would not.

The only downside to this is that if the backend scans the etherscan.io site too frequently, it would be considered a bad robot. Limiting it to once every 24 hours should be OK.

**Comment by meisser** [comment] 2018-12-16 12:36
At the very least, it should be possible to provide clients with a direct link to the swap interface.

Today, it goes like this:
1. Tell user to go to https://uniswap.exchange/swap
2. Tell user to add a token address, e.g. 0xB4272071eCAdd69d933AdcD19cA99fe80664fc08
3. Tell user to select that token

I would prefer to be able to just provide the client with a link like this:
https://uniswap.exchange/swap?token=0xB4272071eCAdd69d933AdcD19cA99fe80664fc08

What do you think?

**Comment by haydenadams** [comment] 2018-12-16 23:45
@gonchs Planning on using localstorage 

@meisser Also planning on doing the linking thing.

Also a good option for low market cap tokens is to set up a fork with their token on top of the list. For example:

https://0xbitcoin.trade/swap

**Comment by A-w-K** [comment] 2019-02-15 08:52
@meisser this is possible once https://github.com/Uniswap/uniswap-frontend/pull/220 is merged

**Comment by thedavidmeister** [comment] 2019-05-15 23:13
i ran into this over at https://github.com/Uniswap/uniswap-frontend/pull/278

> The problem is there is nothing to stop someone from creating a fake version of an existing token (ie duplicate the DAI contract), and deploying an exchange for it. It would be impossible to discern between the two, but users could be tricked into buying fake DAI.

provide the full list sorted by heuristics that are hard to fake?

e.g. ETH liquidity-blocks (multiply liquidity by number of blocks liquidity was provided)
or even just current ETH for a pair

other heuristics could be displayed in the UI

core to DeFi is treating users with enough respect to trust and allow them to make their own decisions, _and_ provide the information/transparency required for them to meaningfully make decisions

provide a "badge" or similar that follows a vetting process, "real DAI" can have a big flashing "official" gif on it

then the GUI could clearly differentiate between tiers of pairs that have been audited via. PRs in github in a pseudo-decentralised way and those that are fully decentralised but are "caveat emptor" to some degree

right now, anything that isn't vetted simply doesn't appear... or it does, but through a weird hacky workaround where users have to manually paste a contract into the UI

the current workaround makes it _easier_ for phishing attacks against smaller markets because an attacker can simply tell users to paste a contract into the GUI and there's no other contextual information provided (e.g. maybe there's a different contract with way more liquidity elsewhere)

another option could be to create a small protocol to map contracts to domains

if a domain(s) can optionally be associated with the contracts somehow then the GUI can hit `https://<contract-domain>/uniswap-contract` or look for a DNS entry or similar that needs to return the contract address

> For now the top 250 ERC20 tokens by market cap with exchanges and liquidity are added to the example/default list maintained in this github repo. Anyone hosting a fork can create their own rules. A good option for low market cap tokens is to set up a fork with their token on top of the list.

following a rule like this doesn't empower uniswap to drive new markets, it always has to follow centralised exchanges, it also doesn't empower people to bootstrap markets in a decentralised way

i find it hard to reconcile the idea of recommending forks to support niche markets while simultaneously holding onto the desire to make it hard for people to create fake versions of existing tokens - imo this approach only shifts and exacerbates the problem by _encouraging_ near-dupes of the whole uniswap domain, incidentally legitimising phishing attacks that are unfortunately incredibly common in crypto :(

uniswap is rather uniquely positioned to offer niche/bootstrapping tokens liquidity without first dragging communities through the scamtastic world of centralised exchanges full of listing fees, "hacks", exit scams, etc. >.<

imagine a world where uniswap liquidity is a deciding factor of whether centralised exchanges list a new token, rather than vice versa!

maybe i'm being overly idealistic... i am excited about what uniswap could be :)

**Comment by thedavidmeister** [comment] 2019-05-15 23:30
for an example of what i'm talking about with niche markets, check out C20 token

- delisted several times from other exchanges due to "low liquidity"
- intentionally small market cap as it is a closed "index fund" style token
- currently listed on uniswap.exchange with ~20 ETH liquidity
- clearly a security token by SEC rules, so EtherDelta-esque risks if manually vetted here
- intentionally designed to be held rather than actively traded
- intentionally one of several tokens from invictus

C20 is in the top 250, but other tokens from invictus (IHF and C10) wouldn't register, but do share the same community

**Comment by haydenadams** [comment] 2019-05-16 00:47
@thedavidmeister Thanks for the feedback and insight. We agree with your premise here:

> core to DeFi is treating users with enough respect to trust and allow them to make their own decisions, and provide the information/transparency required for them to meaningfully make decisions

Just want to let you know we are thinking a lot about the topic of token discoverability - and will likely be making significant improvements on this front soon.

**Comment by thedavidmeister** [comment] 2019-05-16 00:59
@haydenadams 

awesome!

i liked your interview on the unconfirmed podcast a few months ago, it really got me :thinking:

**Comment by osyed** [comment] 2019-05-16 14:52
If you want to make it easy for your users to trade your token from your website, the Shardus team has created and made available a web widget that interfaces with the Uniswap contracts which you can customize and embed into your website. You can find it here:  https://gitlab.com/shardus/uniswap-widget

You can see it in use on the https://Shardus.com website; scroll down to the Token section.

**Comment by osyed** [comment] 2019-08-23 00:28
The Shardus team has created a new interface to the Uniswap contracts which allows the user to see all the tokens that are listed rather than limiting it to a curated list. We have provided users with sufficient information about the token so they can decide on their own if it is the token they wanted to trade and distinguish it from impostors.  You can find the interface here: https://gitlab.com/shardus/uniswapdex and a website hosting it here: https://uniswapdex.com/

It is very easy to host the site on your own server. Instructions provided in the README of the repo.

**Comment by x5engine** [comment] 2020-02-14 20:39
this is a real issue :)

**Comment by moodysalem** [comment] 2020-08-26 20:32
See https://tokenlists.org/!

**Closed by moodysalem** 2020-08-26 20:32 UTC
