### ISSUE TITLE
Liquidity and Unclaimed Fees showing up as $-

### ISSUE THREAD

**Issue by jab416171** [Uniswap/uniswap-interface#1699] opened 2021-05-24 23:25 UTC
**Bug Description**
Open up https://app.uniswap.org/#/pool/6436 and notice the $-

**Steps to Reproduce**

1. Go to https://app.uniswap.org/#/pool/6436
   ...

**Expected Behavior**
Fees and Liquidity should show a dollar amount

**Comment by jab416171** [comment] 2021-05-24 23:26
As a side note, the position is missing from info.uniswap.org: https://info.uniswap.org/#/tokens/0x8FfE40A3D0f80C0CE6b203D5cDC1A6a86d9AcaeA

**Comment by moodysalem** [comment] 2021-05-25 14:06
We probably can't get the dollar value of the IGG token because it's not liquid enough. 
![image](https://user-images.githubusercontent.com/7897876/119511791-611c6080-bd38-11eb-839d-e0f78278dfca.png)

The way our pricing works (recently updated) is we try to get an exact output trade to 100k USDC, and then use the mid price of the route we found.

**Comment by BevOnline** [comment] 2021-05-26 00:09
Would it be possible to allow pricing to be queried from v2 if the pair exists there?

**Comment by BevOnline** [comment] 2021-05-26 00:10
> We probably can't get the dollar value of the IGG token because it's not liquid enough.
> ![image](https://user-images.githubusercontent.com/7897876/119511791-611c6080-bd38-11eb-839d-e0f78278dfca.png)
> 
> The way our pricing works (recently updated) is we try to get an exact output trade to 100k USDC, and then use the mid price of the route we found.

Would it be possible to allow pricing to be queried from v2 in the event of it not having enough liquid on v3?

**Comment by moodysalem** [comment] 2021-05-26 14:17
> Would it be possible to allow pricing to be queried from v2 in the event of there not being enough liquid on v3?

We try both V2 and V3

**Comment by BevOnline** [comment] 2021-05-26 18:44
> > Would it be possible to allow pricing to be queried from v2 in the event of there not being enough liquid on v3?
> 
> We try both V2 and V3

https://v2.info.uniswap.org/pair/0x3571e7f516edb1d283d74d2bb56525c9ff059d63 This is the v2 pool for IGG

**Comment by moodysalem** [comment] 2021-05-26 18:52
Gotcha, that would be duplicate of https://github.com/Uniswap/uniswap-interface/issues/1616

But <100k USDC liquidity is pretty low

**Closed by moodysalem** 2021-05-26 18:52 UTC
Labels: bug
