### ISSUE TITLE
Recent Transactions, replaced approval fees stuck as pending

### ISSUE THREAD

**Issue by tonygustafsson** [Uniswap/uniswap-interface#1814] opened 2021-06-05 14:53 UTC
**Bug Description**
When approving a coin for trading, and it takes too long, it's possible to up the fees a bit and make it faster. When doing so, it works perfectly but under Recent Transaction it is stuck as pending.

**Steps to Reproduce**

Approve a coin. Increase the fee to make it faster. It will be stucked as pending even if the coin is approved.

**Expected Behavior**
Duh

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by willhennessy** [comment] 2021-06-07 22:32
Hi tony, did you increase the gas limit on the Approve action or the Swap action?
What transaction is stuck in the "Recent Transactions" list? Approve or Swap?

**Comment by tonygustafsson** [comment] 2021-06-08 06:05
@willhennessy The approve action. It's not actually stuck on chain, but in GUI.

**Comment by moodysalem** [comment] 2021-06-08 11:30
This is a duplicate of https://github.com/Uniswap/uniswap-interface/issues/1016

**Closed** 2021-06-08 11:30 UTC
Labels: bug
