### ISSUE TITLE
Crash report: `TypeError: t.replaceAll is not a function`

### ISSUE THREAD

**Issue by Alibeygi20** [Uniswap/uniswap-interface#2351] opened 2021-09-15 09:45 UTC
## URL
  
https://app.uniswap.org/#/vote

## Error

```
TypeError: t.replaceAll is not a function
```

## Stacktrace

```
TypeError: t.replaceAll is not a function
    at https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:488937
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:488422
    at Object.To [as useMemo] (https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1661571)
    at t.useMemo (https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1581043)
    at Vw (https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:488145)
    at Kw (https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:489901)
    at NA (https://app.uniswap.org/static/js/main.f9f0d330.chunk.js:1:684668)
    at no (https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1656838)
    at zo (https://app.uniswap.org/static/js/3.4087c00c.chunk.js:2:1666405)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 10; Android SDK built for x86 Build/OSM1.180201.023) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "77.0.3865.92",
    "major": "77"
  },
  "engine": {
    "name": "Blink",
    "version": "77.0.3865.92"
  },
  "os": {
    "name": "Android",
    "version": "10"
  },
  "device": {
    "model": "Android SDK built for x86",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by zzmp** [comment] 2021-09-15 17:44
Duplicate of #2308

**Closed by zzmp** 2021-09-15 17:44 UTC
