### ISSUE TITLE
RPC Error: gas required exceeds allowance (12426870) or always failing transaction 

### ISSUE THREAD

**Issue by dwasyluk** [Uniswap/uniswap-interface#1136] opened 2020-09-28 17:24 UTC
**Bug Description**
Trying to withdraw LP tokens from a pool that has plenty of liquidity I receive the following error:

`RPC Error: gas required exceeds allowance (12426870) or always failing transaction` followed by
`estimateGas failed removeLiquidityETHWithPermitSupportingFeeOnTransferTokens` followed by
`This transaction would fail. Please contact support.`

**Steps to Reproduce**
1. Provide liquidity to the CORE (0x62359ed7505efc61ff1d56fef82158ccaffa23d7) - ETH pool
2. Attempt to remove the liquidity. Select 100%, approving CORE by signing the 'APPROVE' prompt in metamask, click 'REMOVE' expecting another metamask prompt.
3. No Metamask prompt. Nothing happens. Javascript errors.
...

**Expected Behavior**
Metamask prompts to sign transaction and LP tokens are exchanged back to ETH and CORE respectively.

**Comment by cagansevencan** [comment] 2020-10-05 21:22
I got exactly the same JS errors trying to remove liquidity for CORE/ETH. Were you able to solve it?

**Comment by cagansevencan** [comment] 2020-10-08 21:11
So the issue wasn't related to Uniswap alone, CORE doesn't allow their tokens to be removed once it is bought.

**Comment by moodysalem** [comment] 2021-01-30 01:18
Duplicate of https://github.com/Uniswap/uniswap-interface/issues/1257

**Closed by moodysalem** 2021-01-30 01:18 UTC
Labels: bug

**Comment by Tim5123** [comment] 2021-05-29 20:11
> So the issue wasn't related to Uniswap alone, CORE doesn't allow their tokens to be removed once it is added for liquidity.

@cagansevencan I'm wondering what a contract must implement to allow removal / to disallow a removal. Would you know?
