### ISSUE TITLE
Allow to turn off fix ratio when Add or Remove Liquidity

### ISSUE THREAD

**Issue by gkucmierz** [Uniswap/uniswap-interface#1202] opened 2020-11-07 17:19 UTC
**Is your feature request related to a problem? Please describe.**

Sometimes I want to add liquidity, to some pair for example ETH / DAI
There is pretty good liquidity, so when I am adding for example 20 ETH I don't need to worry about my ratio ETH to DAI on the market.
Instead I can add only ETH or only DAI. My contribution will be droplet in the sea so I should not worry about ratio.
Now I am forced to do 2 transactions:
- Swap 10 ETH to DAI
- Add Liquidity: 10 ETH + 10 ETH swapped to DAI

**Describe the solution you'd like**

My proposition is to add checkbox in Add Liquidity / Remove Liquidity forms to turn off market pair price ratio.
And be able to set both amounts by hand.

**Describe alternatives you've considered**

I can't see any alternatives than treating user more serious and let him do let me say "more advance operations"

**Additional context**

<img width="474" alt="Screenshot 2020-11-07 at 18 19 25" src="https://user-images.githubusercontent.com/739084/98447534-c9517f00-2125-11eb-8db0-c75f2f488734.png">

**Comment by moodysalem** [comment] 2020-11-11 15:04
This is a nice documentation of this issue but it is a duplicate of https://github.com/Uniswap/uniswap-interface/issues/1079

**Closed by moodysalem** 2020-11-11 15:04 UTC
Labels: improvement
