### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by shiehso** [Uniswap/uniswap-interface#2107] opened 2021-07-25 07:06 UTC
## URL
  
https://app.uniswap.org/#/add/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2/ETH

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:87112)
    at t.n.sortsBefore (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:75671)
    at https://app.uniswap.org/static/js/main.0bec473b.chunk.js:1:356983
    at Object.Ao [as useMemo] (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:1564133)
    at t.useMemo (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:1483605)
    at Pv (https://app.uniswap.org/static/js/main.0bec473b.chunk.js:1:356956)
    at Yy (https://app.uniswap.org/static/js/main.0bec473b.chunk.js:1:418393)
    at ro (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:1559400)
    at Uo (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:1568967)
    at Vu (https://app.uniswap.org/static/js/4.bc934aa1.chunk.js:2:1612849)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "91.0.4472.164",
    "major": "91"
  },
  "engine": {
    "name": "Blink",
    "version": "91.0.4472.164"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by moodysalem** [comment] 2021-07-26 12:35
Duplicate of https://github.com/Uniswap/uniswap-interface/issues/1763

**Closed by moodysalem** 2021-07-26 12:35 UTC
